### ISSUE TITLE
Question/clarification on resource registration

### ISSUE THREAD

**Issue by lulf** [aerogear/unifiedpush-operator#64]
## Description
In some cases when installing the unifiedpush-operator and enmasse, it may happen that the enmasse api-server is not ready to serve requests for its resources when the unifiedpush-operator is initializing. This leads to a situation where the unifiedpush-operator will print an error message forever until it is restarted.

I noticed that this behavior of ignoring the initialisation error is by design:

https://github.com/aerogear/unifiedpush-operator/blob/master/pkg/controller/unifiedpushserver/unifiedpushserver_controller.go#L150

I would like to understand better why the error is ignored for enmasse resources. 

## Expected Behavior

In general I think it would be better if the operator would handle this error more gracefully by either:

* Exit and let Kubernetes restart the operator if this error happens (as is with the other resources) 
or
* Rerun the initialization process if restarting is not desirable (not sure if this is easy with operator-framework etc.)

Right now it seems a bit fragile in the event of temporal unavailability of its dependencies.

## Actual Behavior

The initial error at startup:

```
"level":"error","ts":1566381664.789352,"logger":"kubebuilder.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"MessagingUser.user.enmasse.io","error":"no
 matches for kind \"MessagingUser\" in version \"user.enmasse.io/v1beta1\"","stacktrace":"github.com/aerogear/unifiedpush-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/jenkins/workspace/unifiedpush-operator_master-DF7SJ5FGYO7GEQL3FA7SNYZRNGLKQOOV3UPT3LR5REZ6UGH2IQCQ/src/github.com/aerogear/unifiedpush-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/aerogear/unifiedpush-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/home/jenkins/workspace/unifiedpush-operator_master-DF7SJ5FGYO7GEQL3FA7SNYZRNGLKQOOV3UPT3LR5REZ6UGH2IQCQ/src/github.com/aerogear/unifiedpush-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:89\ngithub.com/aerogear/unifiedpush-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch\n\t/home/jenkins/workspace/unifiedpush-operator_master-DF7SJ5FGYO7GEQL3FA7SNYZRNGLKQOOV3UPT3LR5REZ6UGH2IQCQ/src/github.com/aerogear/unifiedpush-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122\ngithub.com/aerogear/unifiedpush-operator/pkg/controller/unifiedpushserver.add\n\t/home/jenkins/workspace/unifiedpush-operator_master-DF7SJ5FGYO7GEQL3FA7SNYZRNGLKQOOV3UPT3LR5REZ6UGH2IQCQ/src/github.com/aerogear/unifiedpush-operator/pkg/controller/unifiedpushserver/unifiedpushserver_controller.go:146\ngithub.com/aerogear/unifiedpush-operator/pkg/controller/unifiedpushserver.Add\n\t/home/jenkins/workspace/unifiedpush-operator_master-DF7SJ5FGYO7GEQL3FA7SNYZRNGLKQOOV3UPT3LR5REZ6UGH2IQCQ/src/github.com/aerogear/unifiedpush-operator/pkg/controller/unifiedpushserver/unifiedpushserver_controller.go:43\ngithub.com/aerogear/unifiedpush-operator/pkg/controller.AddToManager\n\t/home/jenkins/workspace/unifiedpush-operator_master-DF7SJ5FGYO7GEQL3FA7SNYZRNGLKQOOV3UPT3LR5REZ6UGH2IQCQ/src/github.com/aerogear/unifiedpush-operator/pkg/controller/controller.go:13\nmain.main\n\t/home/jenkins/workspace/unifiedpush-operator_master-DF7SJ5FGYO7GEQL3FA7SNYZRNGLKQOOV3UPT3LR5REZ6UGH2IQCQ/src/github.com/aerogear/unifiedpush-operator/cmd/manager/main.go:139\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"}
```

Followed by the following error message printed periodically:

```
{"level":"error","ts":1566381739.346736,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"unifiedpushserver-controller","request":"mobile-unifiedpush/unifiedpush","error":"no matches for kind \"MessagingUser\" in version \"user.enmasse.io/v1beta1\"","stacktrace":"github.com/aerogear/unifiedpush-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/jenkins/workspace/unifiedpush-operator_master-DF7SJ5FGYO7GEQL3FA7SNYZRNGLKQOOV3UPT3LR5REZ6UGH2IQCQ/src/github.com/aerogear/unifiedpush-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/aerogear/unifiedpush-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/jenkins/workspace/unifiedpush-operator_master-DF7SJ5FGYO7GEQL3FA7SNYZRNGLKQOOV3UPT3LR5REZ6UGH2IQCQ/src/github.com/aerogear/unifiedpush-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\ngithub.com/aerogear/unifiedpush-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/jenkins/workspace/unifiedpush-operator_master-DF7SJ5FGYO7GEQL3FA7SNYZRNGLKQOOV3UPT3LR5REZ6UGH2IQCQ/src/github.com/aerogear/unifiedpush-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/aerogear/unifiedpush-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/jenkins/workspace/unifiedpush-operator_master-DF7SJ5FGYO7GEQL3FA7SNYZRNGLKQOOV3UPT3LR5REZ6UGH2IQCQ/src/github.com/aerogear/unifiedpush-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/aerogear/unifiedpush-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/jenkins/workspace/unifiedpush-operator_master-DF7SJ5FGYO7GEQL3FA7SNYZRNGLKQOOV3UPT3LR5REZ6UGH2IQCQ/src/github.com/aerogear/unifiedpush-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/aerogear/unifiedpush-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/home/jenkins/workspace/unifiedpush-operator_master-DF7SJ5FGYO7GEQL3FA7SNYZRNGLKQOOV3UPT3LR5REZ6UGH2IQCQ/src/github.com/aerogear/unifiedpush-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

## Environment

* Operating system: ?
* OpenShift versions: 3.11
* Project Versions: 0.1.1

## Steps to reproduce

1. Deploy unifiedpush-operator
2. Deploy enmasse

**Comment by secondsun** [comment]
I'm not sure why we don't worry about the resource not being ready, I think that is a questiong for @grdryn.  However we're recreating the client to bypass the caches that get setup now here : https://github.com/aerogear/unifiedpush-operator/pull/65 which in theory should get fresh resources even if enmasse was previously not ready.

**Comment by grdryn** [comment]
The reason that we ignore errors with the enmasse kinds not being available is that our CR spec exposes an optional `useMessageBroker` boolean option, since we currently also support deployment of UPS without using enmasse at all. @secondsun should we change that to always require it?

@lulf a semi-related question, but for the enmasse side of the equation:

> it may happen that the enmasse api-server is not ready to serve requests for its resources when the unifiedpush-operator is initializing. This leads to a situation where the unifiedpush-operator will print an error message forever until it is restarted.

Could those enmasse kinds be made into proper CRDs? We don't expect enmasse or its operator to respond immediately, but some of the problem as I see it is that these kinds are not fully CRDs somehow, so aren't made available on the cluster until the enmasse api-server is ready. Is my understanding correct?

Here was my previous attempt in the integreatly installation repo to try to block until all of those kinds were available before deploying the unifiedpush-operator, but it seems that wasn't sufficient either: https://github.com/integr8ly/installation/pull/835

**Comment by lulf** [comment]
@grdryn @secondsun I think with the client bypassing the cache, it should be working fine both with and without (though you get some errors in the log perhaps :))

@grdryn Longer term we might make the resources CRDs, but it is a significant effort on our end, particularily for Address and MessagingUser resources.

Feel free to close this issue, it was more of a question anyway

**Comment by grdryn** [comment]
Thanks for the info, I'll close this for now then. :+1:
